spring.application.name=MikhuApp

spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/BD_MikhuApp
spring.datasource.username=postgres
spring.datasource.password=73638301
spoonacular.api.url=https://api.spoonacular.com/recipes/findByIngredients
spoonacular.api.key=${SPOONACULAR_API_KEY}